package it.italiangrid.portal.dbapi.domain;

// Generated 31-lug-2012 9.51.24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notify generated by hbm2java
 */
@Entity
@Table(name = "notify", catalog = "PortalUser")
public class Notify implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 867488583934347958L;
	private int idNotify;
	private UserInfo userInfo;
	private String proxyExpire;

	public Notify() {
	}

	public Notify(UserInfo userInfo) {
		this.userInfo = userInfo;
		this.proxyExpire = "false";
	}

	public Notify(UserInfo userInfo, String proxyExpire) {
		this.userInfo = userInfo;
		this.proxyExpire = proxyExpire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idNotify", unique = true, nullable = false)
	public int getIdNotify() {
		return this.idNotify;
	}

	public void setIdNotify(int idNotify) {
		this.idNotify = idNotify;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@Column(name = "proxyExpire", length = 5)
	public String getProxyExpire() {
		return this.proxyExpire;
	}

	public void setProxyExpire(String proxyExpire) {
		this.proxyExpire = proxyExpire;
	}

}
