package it.italiangrid.portal.dbapi.domain;

// Generated 20-mar-2013 11.03.14 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SshKeys generated by hbm2java
 */
@Entity
@Table(name = "sshKeys", catalog = "PortalUser")
public class SshKeys implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1570926488854301486L;
	private int idKey;
	private UserInfo userInfo;
	private byte[] keyField;

	public SshKeys() {
	}

	public SshKeys(UserInfo userInfo, byte[] keyField) {
		this.userInfo = userInfo;
		this.keyField = keyField;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idKey", unique = true, nullable = false)
	public int getIdKey() {
		return this.idKey;
	}

	public void setIdKey(int idKey) {
		this.idKey = idKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@Column(name = "keyField")
	public byte[] getKeyField() {
		return this.keyField;
	}

	public void setKeyField(byte[] keyField) {
		this.keyField = keyField;
	}

}
