package it.italiangrid.portal.dbapi.domain;

// Generated 23-gen-2012 12.27.05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import it.italiangrid.portal.dbapi.domain.Certificate;
import it.italiangrid.portal.dbapi.domain.UserInfo;
import it.italiangrid.portal.dbapi.domain.UserToVoId;
import it.italiangrid.portal.dbapi.domain.Vo;

/**
 * UserToVo generated by hbm2java
 */
@Entity
@Table(name = "userToVO", catalog = "PortalUser")
public class UserToVo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5434829959406617889L;
	private UserToVoId id;
	private Vo vo;
	private UserInfo userInfo;
	private String isDefault;
	private String fqans;
	private Certificate certificate;

	public UserToVo() {
	}

	public UserToVo(UserToVoId id, Vo vo, UserInfo userInfo) {
		this.id = id;
		this.vo = vo;
		this.userInfo = userInfo;
	}

	public UserToVo(UserToVoId id, Vo vo, UserInfo userInfo, String isDefault,
			String fqans, Certificate certificate) {
		this.id = id;
		this.vo = vo;
		this.userInfo = userInfo;
		this.isDefault = isDefault;
		this.fqans = fqans;
		this.certificate = certificate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "userId", nullable = false)),
			@AttributeOverride(name = "idVo", column = @Column(name = "idVO", nullable = false)) })
	public UserToVoId getId() {
		return this.id;
	}

	public void setId(UserToVoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVO", nullable = false, insertable = false, updatable = false)
	public Vo getVo() {
		return this.vo;
	}

	public void setVo(Vo vo) {
		this.vo = vo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false, insertable = false, updatable = false)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@Column(name = "isDefault", length = 5)
	public String getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "FQANs", length = 65535)
	public String getFqans() {
		return this.fqans;
	}

	public void setFqans(String fqans) {
		this.fqans = fqans;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCert", nullable = false)
	public Certificate getCertificate(){
		return this.certificate;
	}
	
	public void setCertificate(Certificate certificate) {
		this.certificate = certificate;
	}
}
