package it.italiangrid.portal.dbapi.domain;

// Generated 23-gen-2012 12.27.05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import it.italiangrid.portal.dbapi.domain.Idp;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "userInfo", catalog = "PortalUser")
public class UserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1994989181186620092L;
	private int userId;
	private String firstName;
	private String lastName;
	private String institute;
	private String phone;
	private String mail;
	private Idp idp;
	private String username;
	private String registrationComplete;
	private String persistentId;

	public UserInfo() {
	}

	public UserInfo(String firstName, String lastName, String institute,
			String mail, Idp idp, String username, String registrationComplete, String persistentId) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.institute = institute;
		this.mail = mail;
		this.idp = idp;
		this.username = username;
		this.registrationComplete = registrationComplete;
		this.persistentId = persistentId;
	}

	public UserInfo(String firstName, String lastName, String institute,
			String phone, String mail, Idp idp, String username,
			String registrationComplete, String persistentId) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.institute = institute;
		this.phone = phone;
		this.mail = mail;
		this.idp = idp;
		this.username = username;
		this.registrationComplete = registrationComplete;
		this.persistentId = persistentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "firstName", nullable = false, length = 75)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 75)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "institute", nullable = false, length = 75)
	public String getInstitute() {
		return this.institute;
	}

	public void setInstitute(String institute) {
		this.institute = institute;
	}

	@Column(name = "phone", length = 75)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "mail", nullable = false, length = 75)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idp", nullable = true)
	public Idp getIdp() {
		return this.idp;
	}

	public void setIdp(Idp idp) {
		this.idp = idp;
	}

	@Column(name = "username", nullable = false, length = 75)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "registrationComplete", nullable = false, length = 5)
	public String getRegistrationComplete() {
		return this.registrationComplete;
	}

	public void setRegistrationComplete(String registrationComplete) {
		this.registrationComplete = registrationComplete;
	}
	
	@Column(name = "persistentId", nullable = true, length = 100)
	public String getPersistentId() {
		return this.persistentId;
	}

	public void setPersistentId(String persistentId) {
		this.persistentId = persistentId;
	}

	@Override
	public String toString() {
		return "UserInfo [userId=" + userId + ", firstName=" + firstName
				+ ", lastName=" + lastName + ", institute=" + institute
				+ ", phone=" + phone + ", mail=" + mail + ", idp=" + idp
				+ ", username=" + username + ", registrationComplete="
				+ registrationComplete + ", persistentId=" + persistentId + "]";
	}
	
}
